### ISSUE TITLE
真机上拖拽时，大概率会丢失焦点，非常快速的就touchend了

### ISSUE THREAD

**Issue by jiazufei1** [QuintGao/GKSliderView#1]
[LilyVideoPlayerControlView.swift:funciton:sliderTouchBegan(_:):line:525]- sliderTouchBegan
[LilyVideoPlayerControlView.swift:funciton:sliderTouchEnded(_:):line:535]- sliderTouchEnded

**Comment by jiazufei1** [comment]
扩大到100 也无效，依然会丢失![image](https://user-images.githubusercontent.com/56622810/102572597-81137c80-4127-11eb-9a9d-923c1e76b345.png)

**Comment by jiazufei1** [comment]
// 重写此方法将按钮的点击范围扩大
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent *)event {
    CGRect bounds = self.bounds;
    
    // 扩大点击区域
    bounds = CGRectInset(bounds, -100, -100);
    
    // 若点击的点在新的bounds里面。就返回yes
    return CGRectContainsPoint(bounds, point);
}

**Comment by jiazufei1** [comment]
我的手指并没有离开屏幕，也没离开sliderBtn

[LilyVideoPlayerControlView.swift:funciton:sliderTouchBegan(_:):line:525]- sliderTouchBegan
[11:57:01] -[GKSliderView sliderBtnTouchEndedCancel:] [第326行]: sliderBtnTouchEndedCancel
[LilyVideoPlayerControlView.swift:funciton:sliderTouchEnded(_:):line:535]- sliderTouchEnded
[LilyVideoPlayerControlView.swift:funciton:sliderTouchBegan(_:):line:525]- sliderTouchBegan
[11:57:01] -[GKSliderView sliderBtnTouchEndedCancel:] [第326行]: sliderBtnTouchEndedCancel
[LilyVideoPlayerControlView.swift:funciton:sliderTouchEnded(_:):line:535]- sliderTouchEnded
[LilyVideoPlayerControlView.swift:funciton:sliderTouchBegan(_:):line:525]- sliderTouchBegan
[11:57:01] -[GKSliderView sliderBtnTouchEndedCancel:] [第326行]: sliderBtnTouchEndedCancel
[LilyVideoPlayerControlView.swift:funciton:sliderTouchEnded(_:):line:535]- sliderTouchEnded
[LilyVideoPlayerControlView.swift:funciton:sliderTouchBegan(_:):line:525]- sliderTouchBegan
[11:57:01] -[GKSliderView sliderBtnTouchEndedCancel:] [第326行]: sliderBtnTouchEndedCancel
[LilyVideoPlayerControlView.swift:funciton:sliderTouchEnded(_:):line:535]- sliderTouchEnded

**Comment by QuintGao** [comment]
当时只处理了DragInside，加上[_sliderBtn addTarget:self action:@selector(sliderBtnDragMoving:event:) forControlEvents:UIControlEventTouchDragOutside]; 这个就好了
