### ISSUE TITLE
滑块按钮实时位置计算有偏差

### ISSUE THREAD

**Issue by eryuxinling** [QuintGao/GKSliderView#2]
按钮的位置如果用(self.sliderBtn.gk_width) * value是有问题的，当value = 0.5时位于进度条右侧&左偏移按钮宽度的一半，当value != 0.5，左偏移的宽度就不是按钮的宽度的一半，所以显示是有一些误差的(按钮比较大的时候，更为明显)。
self.sliderBtn.gk_left = (self.gk_width - 2 * self.ignoreMargin - self.sliderBtn.gk_width) * value + self.ignoreMargin;
修改为：
self.sliderBtn.gk_left = (self.gk_width - 2 * self.ignoreMargin) * value - self.sliderBtn.gk_width / 2.0 + self.ignoreMargin;

**Comment by QuintGao** [comment]
我这样做是为了让按钮不超过滑杆，可以看看系统的也是这样
