### ISSUE TITLE
有个进度条UI不准问题（就左边的进度度条会出现左移现象。  就我左边距20，GKSliderView控件是一直左边距20. 但里面的sliderProgressView进度条UI会超出控件，慢慢偏移。）

### ISSUE THREAD

**Issue by wscqs** [QuintGao/GKSliderView#3]
我直接这样处理先修复 ：
self.sliderProgressView.gk_width = finishValue;
下面加self.sliderProgressView.gk_left = 0;

**Comment by QuintGao** [comment]
没搞明白什么意思，有demo吗

**Comment by wscqs** [comment]
来信已经收到。

**Comment by wscqs** [comment]
![efdc929d6450a7e904c17d2207d3b9fc](https://github.com/QuintGao/GKSliderView/assets/13110076/1dc82036-a330-429f-bf7e-3b8d4d678b3e)
![3230854831](https://github.com/QuintGao/GKSliderView/assets/13110076/08a0d6af-a807-4767-bfd5-88716bcd8e4b)

**Comment by wscqs** [comment]
demo写在项目，不好抽离。  这UI效果可以借鉴下（一般10秒左右那种短视频列表比较容易复现）。

**Comment by QuintGao** [comment]
在我demo上试试怎么复现也可以，我这没复现出来

**Comment by wscqs** [comment]
你看下我发的图，我能确定是你的控件问题（sliderProgressView会左移）。   不好复现（我项目是用xib布局），我先按我自己解决方案运行。
