### ISSUE TITLE
主动滑动 cpu 爆涨100% 。卡死

### ISSUE THREAD

**Issue by htyo** [QuintGao/GKSliderView#4]
- (instancetype)initWithFrame:(CGRect)frame lineHeight:(CGFloat)lineHeight {
    if (self = [super initWithFrame:frame]) {
        _lineHeight = lineHeight;
        self.backgroundColor = kLineLoadingColor;
        self.center = CGPointMake(frame.size.width * 0.5, frame.size.height * 0.5);
        self.bounds = CGRectMake(0, 0, 1.0f, lineHeight);
    }
    return self;
}

- (void)layoutSubviews {
    [super layoutSubviews];
    
    CGRect frame = self.superview.frame;
    self.center = CGPointMake(frame.size.width * 0.5, frame.size.height * 0.5);
    self.bounds = CGRectMake(0, 0, 1.0f, _lineHeight);
    
    CAAnimationGroup *animationGroup = [self.layer animationForKey:@"lineLoading"];
    CABasicAnimation *scaleAnimation = (CABasicAnimation *)animationGroup.animations.firstObject;
    if (scaleAnimation) {
        scaleAnimation.toValue = @(1.0f * frame.size.width);
    }
}

**Comment by htyo** [comment]
<img width="435" alt="截屏2024-06-03 16 53 32" src="https://github.com/QuintGao/GKSliderView/assets/50307645/23fc4740-5b28-4626-a20f-f77ed25b7728">
我的修改是 将动画 放到一个子视图上，解决cpu爆问题。希望对你有帮助

**Comment by QuintGao** [comment]
最新版已修复
